import { useMemo, useState } from 'react'
import './App.css'

type Status = 'not_started' | 'assigned' | 'in_progress' | 'submitted' | 'approved' | 'rejected'
type Mode = 'manager' | 'employee'
type WorkItem = { stage: string; status: Status; assignee: string; urgent?: boolean; reason?: string; lastUpdate: string }
type Job = { id: string; customer: string; market: string; address: string; priority: 'high' | 'normal' | 'low'; items: Record<string, WorkItem> }

const stages = ['Request', 'Survey', 'Design', 'QC', 'Permit', 'Construction']
const initialJobs: Job[] = [
  { id: 'AZ-1234', customer: 'Copper Ridge Homes', market: 'Phoenix', address: '1840 E. Thomas Rd', priority: 'high', items: { Request: { stage: 'Request', status: 'approved', assignee: 'Maya Chen', lastUpdate: 'Yesterday' }, Survey: { stage: 'Survey', status: 'in_progress', assignee: 'Scott R.', urgent: true, lastUpdate: '9 min ago' }, Design: { stage: 'Design', status: 'assigned', assignee: 'Nina Patel', lastUpdate: '42 min ago' }, QC: { stage: 'QC', status: 'not_started', assignee: 'Unassigned', lastUpdate: 'Not started' } } },
  { id: 'AZ-1277', customer: 'Desert View HOA', market: 'Mesa', address: '3220 S. Signal Butte', priority: 'normal', items: { Request: { stage: 'Request', status: 'approved', assignee: 'Maya Chen', lastUpdate: 'Mon' }, Survey: { stage: 'Survey', status: 'submitted', assignee: 'Scott R.', lastUpdate: '1 hr ago' }, Design: { stage: 'Design', status: 'not_started', assignee: 'Unassigned', lastUpdate: 'Not started' } } },
  { id: 'CO-0842', customer: 'Northline Properties', market: 'Denver', address: '7400 W. 38th Ave', priority: 'low', items: { Request: { stage: 'Request', status: 'approved', assignee: 'Maya Chen', lastUpdate: 'Tue' }, Survey: { stage: 'Survey', status: 'rejected', assignee: 'Jordan Lee', reason: 'Missing pole photos - please reshoot bays 3-4.', lastUpdate: '40 min ago' }, Design: { stage: 'Design', status: 'not_started', assignee: 'Unassigned', lastUpdate: 'Not started' }, QC: { stage: 'QC', status: 'not_started', assignee: 'Unassigned', lastUpdate: 'Not started' }, Permit: { stage: 'Permit', status: 'assigned', assignee: 'Nina Patel', lastUpdate: '2 hrs ago' } } },
  { id: 'AZ-1310', customer: 'Suncrest Retail', market: 'Tempe', address: '610 S. Mill Ave', priority: 'normal', items: { Request: { stage: 'Request', status: 'submitted', assignee: 'Maya Chen', lastUpdate: '25 min ago' }, Survey: { stage: 'Survey', status: 'approved', assignee: 'Jordan Lee', lastUpdate: 'Yesterday' }, Construction: { stage: 'Construction', status: 'in_progress', assignee: 'Scott R.', lastUpdate: '3 hrs ago' } } },
]
const statusLabels: Record<Status, string> = { not_started: 'Not started', assigned: 'Assigned', in_progress: 'In progress', submitted: 'Submitted', approved: 'Approved', rejected: 'Rejected' }

function App() {
  const [mode, setMode] = useState<Mode>('manager')
  const [jobs, setJobs] = useState(initialJobs)
  const [selected, setSelected] = useState<{ jobId: string; stage: string } | null>({ jobId: 'AZ-1234', stage: 'Survey' })
  const [search, setSearch] = useState('')
  const [toast, setToast] = useState('')
  const visibleJobs = useMemo(() => jobs.filter((job) => `${job.id} ${job.customer} ${job.market}`.toLowerCase().includes(search.toLowerCase())), [jobs, search])
  const selectedJob = jobs.find((job) => job.id === selected?.jobId)
  const selectedItem = selectedJob && selected ? selectedJob.items[selected.stage] : undefined
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2400) }
  const updateStatus = (status: Status, jobId = selected?.jobId, stage = selected?.stage) => {
    if (!jobId || !stage) return
    setJobs((current) => current.map((job) => job.id !== jobId ? job : { ...job, items: { ...job.items, [stage]: { ...job.items[stage], status, lastUpdate: 'Just now' } } }))
    notify(`${stage} marked ${statusLabels[status].toLowerCase()}`)
  }
  const updateUrgency = () => {
    if (!selected || !selectedItem) return
    setJobs((current) => current.map((job) => job.id !== selected.jobId ? job : { ...job, items: { ...job.items, [selected.stage]: { ...selectedItem, urgent: false } } }))
    notify('Urgent flag cleared')
  }

  return (
    <div className={`app-shell ${mode === 'employee' ? 'employee-mode' : ''}`}>
      <header className="topbar"><div className="brand"><div className="brand-mark"><span>S</span><span>I</span><span>E</span></div><div><strong>TaskGrid</strong><small>by SIE</small></div></div><div className="topbar-actions"><button className="mode-switch" onClick={() => setMode(mode === 'manager' ? 'employee' : 'manager')}><span className="avatar">{mode === 'manager' ? 'MC' : 'SR'}</span> View as {mode === 'manager' ? 'employee' : 'manager'} <span>v</span></button><button className="icon-button" aria-label="Notifications">Bell <i /></button></div></header>
      {mode === 'employee' ? <EmployeeView jobs={jobs} onBack={() => setMode('manager')} onStart={(jobId, stage) => updateStatus('in_progress', jobId, stage)} onSubmit={(jobId, stage) => updateStatus('submitted', jobId, stage)} /> : <main className="workspace"><div className="page-heading"><div><p className="eyebrow">Operations / Arizona + Colorado</p><h1>Good morning, Maya</h1><p className="muted">Here is what needs your attention across the operation.</p></div><button className="primary-button" onClick={() => notify('New job flow is ready to connect')}>+ New job</button></div><section className="summary-row"><Summary label="Active" value="2" tone="green" detail="moving now" /><Summary label="Waiting" value="4" tone="gold" detail="assigned or queued" /><Summary label="Delayed" value="1" tone="red" detail="needs a nudge" /><Summary label="Needs action" value="3" tone="blue" detail="review today" /></section><div className="toolbar"><div className="tabs"><button className="tab active">All jobs <span>12</span></button><button className="tab">Needs action <span>3</span></button><button className="tab">My team <span>8</span></button></div><label className="search"><span>Search</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Job, customer, market" /></label></div><section className="board-section"><div className="section-heading"><div><p className="eyebrow">Live flow board</p><h2>Work in motion</h2></div><span className="live"><i /> Live updates</span></div><div className="board-wrap"><div className="board-grid board-header"><div className="job-heading">Job <span>4 visible</span></div>{stages.map((stage) => <div key={stage} className="stage-heading">{stage}</div>)}</div>{visibleJobs.map((job) => <div className="board-grid job-row" key={job.id}><button className="job-cell" onClick={() => setSelected({ jobId: job.id, stage: Object.keys(job.items)[0] })}><span className={`priority ${job.priority}`} /><div><strong>{job.id}</strong><small>{job.customer}</small></div></button>{stages.map((stage) => { const item = job.items[stage]; return <button key={stage} className={`work-cell ${item ? `status-${item.status}` : 'empty-cell'}`} onClick={() => setSelected({ jobId: job.id, stage })} aria-label={`${job.id} ${stage} ${item ? statusLabels[item.status] : 'assign ${stage}'}`}>{item ? <><span className="status-dot">{item.status === 'approved' ? '✓' : ''}</span>{item.urgent && <span className="urgent-mark">!</span>}<span className="cell-status">{statusLabels[item.status]}</span></> : <span className="not-applicable">-</span>}</button> })}</div>)}</div><div className="legend"><span><i className="legend-dot green" /> In progress</span><span><i className="legend-dot gold" /> Waiting</span><span><i className="legend-dot blue" /> Submitted</span><span><i className="legend-dot red" /> Needs attention</span><span><i className="legend-check">✓</i> Approved</span></div></section></main>}
      {mode === 'manager' && selected && selectedJob && <aside className="detail-drawer"><button className="close-button" onClick={() => setSelected(null)} aria-label="Close details">x</button><p className="eyebrow">Job detail</p><div className="drawer-job"><span className={`priority ${selectedJob.priority}`} /><div><h2>{selectedJob.id}</h2><p>{selectedJob.customer}</p></div><span className="priority-label">{selectedJob.priority} priority</span></div><div className="job-meta"><span><b>Market</b>{selectedJob.market}</span><span><b>Address</b>{selectedJob.address}</span></div><div className="drawer-rule" /><div className="drawer-stage"><div><p className="eyebrow">Selected work item</p><h3>{selected.stage}</h3></div>{selectedItem?.urgent && <span className="urgent-badge">! Urgent</span>}</div>{selectedItem ? <><div className={`large-status status-${selectedItem.status}`}><span className="status-dot">{selectedItem.status === 'approved' ? '✓' : ''}</span><div><b>{statusLabels[selectedItem.status]}</b><span>{selectedItem.assignee}</span></div></div>{selectedItem.reason && <div className="reason"><b>Needs attention</b><p>{selectedItem.reason}</p><small>Returned by Dana, 40 min ago</small></div>}<div className="detail-list"><span><b>Last update</b>{selectedItem.lastUpdate}</span><span><b>Assignee</b>{selectedItem.assignee}</span></div><div className="drawer-actions">{selectedItem.status === 'assigned' && <button className="primary-button full" onClick={() => updateStatus('in_progress')}>Start on behalf</button>}{selectedItem.status === 'in_progress' && <button className="secondary-button full" onClick={() => updateStatus('submitted')}>Mark submitted</button>}{selectedItem.status === 'submitted' && <><button className="primary-button full" onClick={() => updateStatus('approved')}>Approve work</button><button className="danger-button full" onClick={() => updateStatus('rejected')}>Reject with reason</button></>}{selectedItem.status === 'rejected' && <button className="primary-button full" onClick={() => updateStatus('assigned')}>Reassign work</button>}{selectedItem.urgent && <button className="text-button" onClick={updateUrgency}>Clear urgent flag</button>}</div></> : <div className="assign-state"><p>This stage is not part of this job yet.</p><button className="primary-button full" onClick={() => notify(`Assign ${selected.stage} to an employee`)}>Assign into {selected.stage}</button></div>}<div className="timeline"><p className="eyebrow">Activity timeline</p><div className="timeline-item"><span className="timeline-dot green" /><p><b>{selected.stage} updated</b><small>Latest activity for this work item</small></p><time>Now</time></div><div className="timeline-item"><span className="timeline-dot blue" /><p><b>Job created</b><small>{selectedJob.customer} entered the board</small></p><time>Mon</time></div></div></aside>}
      {toast && <div className="toast">{toast}</div>}
    </div>
  )
}

function Summary({ label, value, tone, detail }: { label: string; value: string; tone: string; detail: string }) { return <div className="summary-item"><span className={`summary-dot ${tone}`} /><div><b>{value}</b><span>{label}</span></div><small>{detail}</small></div> }

function EmployeeView({ jobs, onBack, onStart, onSubmit }: { jobs: Job[]; onBack: () => void; onStart: (jobId: string, stage: string) => void; onSubmit: (jobId: string, stage: string) => void }) { const employeeJobs = jobs.flatMap((job) => Object.values(job.items).filter((item) => item.assignee === 'Scott R.').map((item) => ({ job, item }))); return <main className="employee-main"><button className="back-button" onClick={onBack}>← Manager view</button><p className="eyebrow">My work / Tuesday, Aug 29</p><h1>Today's work</h1><p className="muted">Three jobs need your attention.</p><div className="employee-list">{employeeJobs.map(({ job, item }) => <article className={`employee-card ${item.status === 'rejected' ? 'attention-card' : ''}`} key={`${job.id}-${item.stage}`}><div className="employee-card-top"><span className={`priority ${job.priority}`} /><div><span className="job-id">{job.id}</span><h2>{item.stage}</h2><p>{job.customer} · {job.address}</p></div>{item.urgent && <span className="urgent-badge">! Urgent</span>}</div><div className="employee-status"><span className={`status-dot ${item.status}`}>{item.status === 'approved' ? '✓' : ''}</span><span>{statusLabels[item.status]}</span><span className="status-time">{item.lastUpdate}</span></div>{item.reason && <div className="employee-reason"><b>Needs attention</b><p>{item.reason}</p><small>Returned by Dana, 40 min ago</small></div>}<div className="employee-actions">{item.status === 'assigned' && <button className="primary-button" onClick={() => onStart(job.id, item.stage)}>Start</button>}{item.status === 'in_progress' && <><button className="secondary-button" onClick={() => window.alert('Update form is the next MVP slice.')}>Update</button><button className="primary-button" onClick={() => onSubmit(job.id, item.stage)}>Submit</button></>}{item.status === 'rejected' && <button className="primary-button" onClick={() => onStart(job.id, item.stage)}>Resume</button>}</div></article>)}</div></main> }

export default App
